[package]
name = "stm32f446"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
rtt-target = "0.6.1"

[profile.dev]
opt-level = 2
debug = true
codegen-units = 1
lto = false
panic = "abort"

[profile.release]
opt-level = 3
debug = true
codegen-units = 1
lto = true
panic = "abort"